name: Deploy Static Site to GitHub Pages

on:
  # run workflow on push to the main branch
  push:
    branches:
      - main
  # allow manual trigger from the actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      # step 1: check out the code from the repository
      - name: checkout code
        uses: actions/checkout@v4

      # step 2: remove the existing build directory if it exists
      - name: clean build directory
        run: |
          if [ -d build ]; then
            echo "removing existing build directory..."
            rm -rf build
          fi

      # step 3: create the build directory if necessary
      - name: create build directory
        run: mkdir build

      # step 4: deploy the contents of the build folder to github pages
      - name: deploy to github pages
        uses: actions/deploy-pages@v4
        with:
          folder: build
